services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shortener-db
          property: connectionString
      - key: PORT
        value: 4000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-sokratim.onrender.com

databases:
  - name: shortener-db
    plan: free
